language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

install: true
cache:
  directories:
    - "$HOME/.m2"

script:
  - "./mvnw clean package verify -B -q"

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
