sudo: false
language: java

jdk:
  - oraclejdk8

install: true
cache:
  directories:
    - "$HOME/.m2"

script:
  - "./mvnw verify -B -q"
  - "./mvnw clean install"
  - "./mvnw -Danimal.sniffer.skip=true cobertura:cobertura"

after_success:
  - "bash <(curl -s https://codecov.io/bash)"