# Global configuration --------------------------------

[global]
useTempDirectory = true

# Networking configuration ----------------------------

[network]
host = "0.0.0.0"
sendBufferSize = 128

[network.clientApi]
port = 51020
receiveBufferSize = 16
controlMessageRequestTimeoutInMillis = 10000

[network.managementApi]
host = "localhost"
port = 51016
receiveBufferSize = 16

[network.replicationApi]
host = "localhost"
port = 51017
receiveBufferSize = 16

# System Configuration --------------------------------

[threading]
numberOfThreads = 2
maxIdleTimeMs = 100
idleStrategy = "BACKOFF"

# Log Configuration -----------------------------------

[logs]
defaultLogSegmentSize = 512

# Workflow Configuration ------------------------------------------

[workflow]
cacheSize = 1024
maxPayloadSize = 4096
